import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {ThemeProvider} from "@/app/context/themeContext";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rhaissa Zeferino | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen antialiased bg-neutral-100 transition-colors dark:bg-neutral-900 dark:text-white ${geistSans.variable} ${geistMono.variable}`} >
        <ThemeProvider>
        <Navbar/>
        <main className="flex-grow">
            {children}
        </main>
        <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
