import { Course } from '@/types';


export const courses: Course[] = [
    {
        title: 'Python: building efficient systems with SOLID and Design Patterns',
        description: 'Short course focused on building applications following design paterns.',
        technologies: ['Design Patterns', 'SOLID Principles', 'Python'],
        certificateLink: 'https://cursos.alura.com.br/certificate/a5687f43-1112-4583-9ed3-0de1098ae9bd?lang=pt_BR',
        completitionDate: '03/24/2025',
        institution: 'Alura',
    },
    {
        title: 'Clean Code',
        description: 'Focused on writing clean and maintainable code.',
        technologies: ['Python', 'Javascript', 'Clean Code', 'SOLID Principles'],
        certificateLink: 'https://www.udemy.com/certificate/UC-bc73722b-4880-41f0-a8b7-3d46d40b1402/',
        completitionDate: '06/04/2025',
        institution: 'Alura',
    },
   {
        title: 'Visual Design Intensive · Collab Design',
        description: 'Focused on UI, branding, and layout systems.',
        technologies: ['UI Design', 'Photoshop', 'Visual Design', 'Branding'],
        certificateLink: '/courses/Visual_Design_Certificate.pdf',
        completitionDate: '01/30/2021',
        institution: 'Alura',
    },
    {
        title: 'Python: applying best practices with PEP 8',
        description: 'A course focused on applying best practices in Python programming using PEP 8 guidelines.',
        technologies: ['Python', 'PEP 8', 'List Comprehensions', 'Pytest'],
        certificateLink: 'https://cursos.alura.com.br/certificate/733f044c-06af-43e9-b84d-2e30bdc9a300?lang=pt_BR',
        completitionDate: '03/04/2025',
        institution: 'Alura',
    },
    {
        title: 'Python and TDD: exploring unit tests',
        description: 'A course focused on exploring unit testing in Python using TDD principles.',
        technologies: ['Python', 'TDD', 'Unit Testing'],
        certificateLink: 'https://cursos.alura.com.br/certificate/790de163-f345-419d-99a8-35259b06fc45?lang=pt_BR',
        completitionDate: '03/24/2025',
        institution: 'Alura',
    },
    {
        title: 'JavaScript: building dynamic pages',
        description: 'A course focused on building dynamic web pages using JavaScript.',
        technologies: ['JavaScript', 'HTML', 'CSS', 'DOM Manipulation'],
        certificateLink: 'https://cursos.alura.com.br/certificate/47d404ec-2fec-45fc-ac9d-3c675754f480?lang=pt_BR',
        completitionDate: '06/14/2025',
        institution: 'Alura',
    },
    {
        title: 'Bootstrap 5: new features and best practices for HTML, CSS and JavaScript',
        description: 'A course focused on the new features and best practices of Bootstrap 5 for HTML, CSS, and JavaScript.',
        technologies: ['HTML', 'CSS', 'Bootstrap 5', 'JavaScript'],
        certificateLink: 'https://cursos.alura.com.br/certificate/4a3c9107-3849-4cf7-a599-62ab71d981cc?lang=pt_BR',
        completitionDate: '06/08/2025',
        institution: 'Alura',
    },
    {
        title: 'Bootstrap5: create a responsive landing page',
        description: 'A course focused on creating a responsive landing page using Bootstrap 5.',
        technologies: ['HTML', 'CSS', 'Bootstrap 5'],
        certificateLink: 'https://cursos.alura.com.br/certificate/36351a30-f812-4300-97ef-e284e5b4cede?lang=pt_BR',
        completitionDate: '06/06/2025',
        institution: 'Alura',
    },
    {
        title: 'Pandas: getting to know the library',
        description: 'A course focused on getting to know the Pandas library for data manipulation and analysis.',
        technologies: ['Python', 'Pandas', 'Data Analysis'],
        certificateLink: 'https://cursos.alura.com.br/certificate/67133468-7fe1-4b02-add9-66d243c3d6ef?lang=pt_BR',
        completitionDate: '03/19/2025',
        institution: 'Alura',
    },
    {
        title: 'NumPy: efficient numerical analysis with Python',
        description: 'A course focused on getting to know the NumPy library for numerical analysis.',
        technologies: ['Python', 'NumPy', 'Data Analysis'],
        certificateLink: 'https://cursos.alura.com.br/certificate/7d119234-5261-407c-97e9-fe93c6a9dcbb?lang=pt_BR',
        completitionDate: '03/10/2025',
        institution: 'Alura',
    },
    {
        title: 'Python for Data Science: working with functions, data structures and exceptions',
        description: 'A course focused on Python for Data Science, covering functions, data structures, and exception handling.',
        technologies: ['Python', 'Data Science', 'Functions', 'Data Structures', 'Exception Handling'],
        certificateLink: 'https://cursos.alura.com.br/certificate/a09bca86-dbb7-4ff5-8665-b584a74ee52c?lang=pt_BR',
        completitionDate: '02/25/2025',
        institution: 'Alura',
    },
    {
        title: 'Python for Data Science: first steps',
        description: 'An introductory course to Python for Data Science, covering basic concepts and techniques.',
        technologies: ['Python', 'Data Science'],
        certificateLink: 'https://cursos.alura.com.br/certificate/a09bca86-dbb7-4ff5-8665-b584a74ee52c?lang=pt_BR',
        completitionDate: '02/10/2025',
        institution: 'Alura',
    },
    {
        title: 'Python: advance in Object Orientation and consume API',
        description: 'A course focused on advancing object-oriented programming skills in Python and APIs.',
        technologies: ['Python', 'Object Orientation', 'Problem Solving', 'API'],
        certificateLink: 'https://cursos.alura.com.br/certificate/fcdbde47-5725-4a0e-982d-bb6c4dcc7ea7?lang=pt_BR',
        completitionDate: '01/08/2025',
        institution: 'Alura',
    },
    {
        title: 'Python: applying Object Orientation',
        description: 'A course focused on applying object-oriented programming principles in Python.',
        technologies: ['Python', 'Object Orientation', 'Problem Solving'],
        certificateLink: 'https://cursos.alura.com.br/certificate/28cd94f1-c1a2-483a-9b4d-5bf88cfc38c3?lang=pt_BR',
        completitionDate: '01/06/2025',
        institution: 'Alura',
    },
    {
        title: 'Python: create your first application',
        description: 'A hands-on course focused on developing programming logic through practical challenges.',
        technologies: ['Python', 'Technical Skills', 'Problem Solving'],
        certificateLink: 'https://cursos.alura.com.br/certificate/b0459410-2df9-49b7-a512-76ddf5e17c7e?lang=pt_BR',
        completitionDate: '01/02/2025',
        institution: 'Alura',
    },
    {
        title: 'Programming logic: practicing with challenges',
        description: 'A hands-on course focused on developing programming logic through practical challenges.',
        technologies: ['Javascript', 'Programming Logic', 'Problem Solving'],
        certificateLink: 'https://cursos.alura.com.br/certificate/7de2a50e-9d11-40b8-a9dd-1758c41c6fd9?lang=pt_BR',
        completitionDate: '12/26/2024',
        institution: 'Alura',
    },
    {
        title: 'Git and GitHub: sharing and collaborating on projects',
        description: 'An introduction to version control and collaboration using Git and GitHub.',
        technologies: ['Git', 'GitHub', 'Version Control'],
        certificateLink: 'https://cursos.alura.com.br/certificate/b0459410-2df9-49b7-a512-76ddf5e17c7e?lang=pt_BR',
        completitionDate: '12/04/2024',
        institution: 'Alura',
    },
    {
        title: 'Programming logic: explore functions and lists',
        description: 'A course focused on programming logic using functions and lists.',
        technologies: ['JavaScript', 'HTML', 'CSS', 'Programming Logic', 'Problem Solving'],
        certificateLink: 'https://cursos.alura.com.br/certificate/c184a200-3a02-4a2b-bfd1-a8c2b326b58c?lang=pt_BR',
        completitionDate: '12/02/2024',
        institution: 'Alura',
    },
    {
        title: 'Programming logic: immerse yourself in programming with JavaScript',
        description: 'An introduction to programming logic using JavaScript, covering basic concepts and problem-solving techniques.',
        technologies: ['Javascript', 'Programming Principles', 'Best Practices'],
        certificateLink: 'https://cursos.alura.com.br/certificate/2cf4e9e9-cd5a-4b3b-b36c-fd8c95f516a2?lang=pt_BR',
        completitionDate: '12/01/2024',
        institution: 'Alura',
    },
    {
        title: 'Getting started in programming: career and first steps',
        description: 'A comprehensive introduction to programming, covering fundamental concepts and career paths.',
        technologies: ['Career Development'],
        certificateLink: 'https://cursos.alura.com.br/certificate/c0ae04ec-d477-411b-84ee-b88059f6ff9b?lang=pt_BR',
        completitionDate: '11/30/2024',
        institution: 'Alura',
    }
]